### ISSUE TITLE
API getAddresses: pridat ci na adrese obchoduju so statom / alebo tam byva politik

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#110]
Pre adresy ktore obchoduju so statom (na zaklade tabulky tradewithgovernment) treba vracat boolean ze obchoduju so statom.

Podobne mozme v buducnosti pridat boolean pre kontakt s politikou (ked na to budeme mat data).

**Comment by matejbalog** [comment]
Do `GetAddresses` pribudol nový `bool` field `tradewithgovernment`.
