### ISSUE TITLE
Fixnut stakeholder_type_id v related v GetInfos.

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#111]
Aktualne vraciame vztah len jednym smerom, e.g. firma A vlastni firmu B. Chceme vracat aj ze firma B je vlastnena firmou A.

Treba teda pridat aj opacny select z tabulky related.
Inverzny vztah moze mat stakeholder_type_id:= -1 * povodny stakeholder_type_id.

Otazne je ako chceme riesit ak A a B maju viac roznych vztahov. Asi vracajme vsetky a nechajme na frontend ako to zobrazi.

**Comment by matejbalog** [comment]
`GetInfos` už vracia aj informácie o spätných hranách: field `stakeholder_type_id` typu `int` bol nahradený fieldom `edge_types` typu `int[]`, ktorý obsahuje indexy všetkých typov prítomných hrán. Prichádzajúca hrana je reprezentovaná negatívnym indexom.
