### ISSUE TITLE
Fixnut hladanie mena entity bez diakritiky.

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#118]
Zreprodukovanie problemu:

1. psql -d vd      (ako pouzivatel datautils)
2. set search_path="prod_20180819220534";
3. SELECT DISTINCT id AS eid FROM entities WHERE to_tsvector('unaccent', name) @@ plainto_tsquery('unaccent', 'stefan skrucany') limit 5;

Nieco taketo nam v starej databaze verejne funguje. Tam dokonca funguje aj 
select ts_lexize('unaccent','Hôtel');

V novej databaze vd som tiez nainstaloval extension unaccent. Tym, ze pouzivame vo velkom schemy je to ale cele zrejme komplikovanejsie. Funguje vsak aspon
select public.ts_lexize('public.unaccent','Hôtel');

Snazil som sa postupovat aj podla tipov v https://www.postgresql.org/docs/9.1/static/unaccent.html ale nepodarilo sa mi to rozchodit.

**Comment by emempi** [comment]
Ako workaround na niektore veci sa da pouzit:

  set search_path="prod_20180819220534",public;

Toto umozni aspon volat veci ako 
 
  select ts_lexize('unaccent','Hôtel');

Query #3 sa mi nepodarilo nikde korektne vykonat -- vies mi dat priklad, kde zbehne? (tam potom treba pozriet, ako je definovana 'unaccent' text search configuration.

**Comment by lenhardt** [comment]
Ako user verejne:

$ psql -d verejne
verejne=> set search_path="mysql";
verejne=> select eid FROM entities WHERE to_tsvector('unaccent', entity_name) @@ plainto_tsquery('unaccent', 'stefan skrucany') limit 5;
   eid   
---------
  229753
  470858
 1175186
  714768
(4 rows)

**Comment by emempi** [comment]
(sort-of) gotcha:
verejne=# select * from pg_catalog.pg_ts_config;
  cfgname   | cfgnamespace | cfgowner | cfgparser 
------------+--------------+----------+-----------
 simple     |           11 |       10 |      3722
 danish     |           11 |       10 |      3722
 dutch      |           11 |       10 |      3722
 english    |           11 |       10 |      3722
 finnish    |           11 |       10 |      3722
 french     |           11 |       10 |      3722
 german     |           11 |       10 |      3722
 hungarian  |           11 |       10 |      3722
 italian    |           11 |       10 |      3722
 norwegian  |           11 |       10 |      3722
 portuguese |           11 |       10 |      3722
 romanian   |           11 |       10 |      3722
 russian    |           11 |       10 |      3722
 spanish    |           11 |       10 |      3722
 swedish    |           11 |       10 |      3722
 turkish    |           11 |       10 |      3722
 unaccent   |       167667 |       10 |      3722

vd=# select * from pg_catalog.pg_ts_config;
  cfgname   | cfgnamespace | cfgowner | cfgparser 
------------+--------------+----------+-----------
 simple     |           11 |       10 |      3722
 danish     |           11 |       10 |      3722
 dutch      |           11 |       10 |      3722
 english    |           11 |       10 |      3722
 finnish    |           11 |       10 |      3722
 french     |           11 |       10 |      3722
 german     |           11 |       10 |      3722
 hungarian  |           11 |       10 |      3722
 italian    |           11 |       10 |      3722
 norwegian  |           11 |       10 |      3722
 portuguese |           11 |       10 |      3722
 romanian   |           11 |       10 |      3722
 russian    |           11 |       10 |      3722
 spanish    |           11 |       10 |      3722
 swedish    |           11 |       10 |      3722
 turkish    |           11 |       10 |      3722
(16 rows)

Je to trocha cudne, lebo \dF ukazuje tu istu hodnotu pre oba tablespaces. 

Kazdopadne, zaexperimentoval som a (v skratenej forme):
vd=# select oid,nspname from pg_catalog.pg_namespace;
  oid   |                nspname                
--------+---------------------------------------
...
   2200 | public
...
(47 rows)

vd=> insert into pg_catalog.pg_ts_config values('unaccent', 2200, 10, 3722);

Sposobilo, ze query vyssie uz zbieha aspon v takejto forme:

vd=# select id,name FROM entities WHERE to_tsvector('unaccent', name) @@ plainto_tsquery('unaccent', 'stefan skrucany') limit 5;
NOTICE:  text-search query contains only stop words or doesn't contain lexemes, ignored
 id | name 
----+------
(0 rows)

Netusim, ako sa FTS v Postgrese konfiguruje na stopwords/lexemy; mozno som nieco prehliadol. Uz to, ze som toto musel do postgresu dobuchat rucne, je pomerne podozrive :-/ .

**Comment by lenhardt** [comment]
Dik Mino, ze si na to pozrel.

Ak to zhrniem: Teraz to uz pri tom query nedava chybu (ak je v pathu okrem schemy prod_* aj public) ale stale to nedava vysledok.

**Comment by lenhardt** [comment]
v starej db v tabulke entites mame, ked si dam 
\d entities
Table "mysql.entities"
          Column          |       Type       |                       Modifiers                       
--------------------------+------------------+-------------------------------------------------------
 eid                      | integer          | not null
 id                       | integer          | not null default nextval('entities_id_seq'::regclass)
 entity_name              | text             | collate sk_SK.UTF-8

a tiez aj index:
"entities_to_tsvector_idx" gin (to_tsvector('unaccent'::regconfig, entity_name))

v novej nemame ani index ani modifier. index som skusil pridat v novej prod scheme prikazom:
create index entities_to_tsvector_idx on entities using gin (to_tsvector('unaccent'::regconfig, name));
to vyzera ze pridalo dobry index, ale stale to nevracia vysledky, asi bude treba upravit aj ten modifier.

**Comment by lenhardt** [comment]
Skusim v novej tabulke aj alternut column type.
ALTER TABLE entities ALTER COLUMN name TYPE text collate sk_SK;

**Comment by lenhardt** [comment]
Vyzera, ze mi uz funguje query typu

select id, name from entities where to_tsvector(unaccent(name)) @@ plainto_tsquery(unaccent('stefan skrucany')) limit 5;

(problem je vsak rychlost, zrejme sa ten index nepouziva dobre v tomto tvare..)

ale nefunguje  ked pouzivam 'unaccent' ako argument a nie ako funkciu:
to_tsvector('unaccent', entity_name) @@ plainto_tsquery('unaccent', 'stefan skrucany')
