### ISSUE TITLE
a_shortest_path nevracia prepojenia

### ISSUE THREAD

**Issue by jakubukrop** [verejnedigital/verejne.digital#122]
Podla `getInfos` ma Noga vztah k 1 entite (https://verejne.digital/api/v/getInfos?eids=2037250)
```
{
    2037250: {
        name: "Miro Noga",
        related: [{
            name: "AURA PRODUCTION, s.r.o.",
            ...
            eid: 161628,
        }],
        ...
    }
}
```
Avsak `a_shortest_path` tento vztah nenajde:
https://verejne.digital/api/p/a_shortest_path?eid1=2037250&eid2=161628
```[]```

**Comment by jakubukrop** [comment]
Aj subgraph vracia podozrive data
```
{
   distance_from_B: 0, 
   eid: 1062557,
   entity_name: "Jozef Dzedzina",
   distance_from_A: null
}
```
ale v https://verejne.digital/api/v/getInfos?eids=1062557 meno Dzedzina nefiguruje

**Comment by matejbalog** [comment]
Po reštarte aplikácie `prepojenia` prvý uvedený problém zmizol:
https://verejne.digital/api/p/a_shortest_path?eid1=2037250&eid2=161628&cachebreak
`[2037250,161628]`
Na overenie druhého problému by som potreboval parametre pre `subgraph`. @jakubukrop 

Možná príčina problému:
Ak som dobre pozeral, aplikácia `prepojenia` bola predtým naposledy reštartovaná mnou, 20. augusta 01:55 SELČ. To by znamenalo, že po vygenerovaní posledných produkčných dát (začiatok generácie 20. augusta o 22:38) reštartovaná nebola. Nakoľko aplikácia `prepojenia` si drží graf v pamäti, hodnoty `eid` medzi aplikáciou `prepojenia` (servujúcou `a_shortest_path` a `subgraph`) a aplikáciou `verejne` (servujúcou `getInfos`) potom už nemuseli byť konzistentné.

@lenhardt Aplikácia `prepojenia` by sa po vygenerovaní nových produkčných dát asi mala vždy automaticky reštartovať?

**Comment by jakubukrop** [comment]
Graf uz teraz vyzera tiez v poriatku, dik.
