### ISSUE TITLE
Vztah medzi rodinnymi prislusnikmi

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#128]
Pozerajuc na nove data, zdalo sa mi ze v GetInfos chybaju vztahy ludi s rovnakymi menami sidliacimi na spolocnej adrese. (napriklad Slnecna 11 Pezinok)

Treba to skontrolovat, zaroven asi dat tomu vztahu edge_type 0 (mozno toto bol jeden zo zdrojov 'null') nech je obojstranny. Nemusi mat ziadne specialne pomenovanie nateraz.

**Comment by matejbalog** [comment]
Na Slnečnej 11 v Pezinku momentálne vidím len jednu entitu:
```
vd=> SELECT * FROM address WHERE lat=48.2890383;
   id   |    lat     |    lng    |                 address                  
--------+------------+-----------+------------------------------------------
 542209 | 48.2890383 | 17.275924 | Slnečná 894/11, 902 01 Pezinok, Slovakia
(1 row)

vd=> SELECT * FROM entities WHERE address_id=542209;
   id    |       name        | address_id 
---------+-------------------+------------
 2297651 | Lýdia Lenhardtová |     542209
(1 row)
```

**Comment by lenhardt** [comment]
Ak spravne vidim, problem je ze to vobec nemame naprogramovane ;-)

Zo stareho systemu sme preniesli iba deduplikovanie entit. Toto nam chyba. Mal by to byt jeden z post-processingovych krokov, ktory sa zavola na konci (alebo po skonceni) generate_prod_data.
