### ISSUE TITLE
Obstaravania generuju vsetko v jednom datume

### ISSUE THREAD

**Issue by bundala** [verejnedigital/verejne.digital#13]
V sekcii Zobraz podla datumu: https://verejne.digital/obstaravania/index.html su vsetky obstaravania zgrupovane pod jednym datumom (poslednym dnom z ktoreho mame obstaravania). Treba opravit, aby obstaravania boli porozdelovane podla jednotlivych dni -- samostatna tabulka pre jednotlive dni.

**Comment by rajcinky** [comment]
Fixed with https://github.com/verejnedigital/verejne.digital/commit/717ade5f770b1df1a25732cf41c981ee89bc7469
