### ISSUE TITLE
Zbierka malych designovych chyb v prepojeni

### ISSUE THREAD

**Issue by milutin** [verejnedigital/verejne.digital#15]
- [x] Vyhladaj form pri malych displayoch ma 01 a form na 2 riadkoch.
- [x] Nadpis prepojenia.verejne.digital
- [x] fonty zladit
- [x] oranzova farba pre politikov
- [x] mobil zmensit biele stvorce
- [x] opravit link na mapu

**Comment by milutin** [comment]
- [ ] [sidebar vylepsit](https://github.com/verejnedigital/verejne.digital/issues/14)

**Comment by milutin** [comment]
Fonts https://github.com/verejnedigital/verejne.digital/commit/cc53e58347d4f6261a88d4424a1d6f1431791056

**Comment by lenhardt** [comment]
Zobrazovat EURove sumy bez desatinnych ciarok.

Staci fixnut tak ako v https://github.com/verejnedigital/verejne.digital/commit/b66f9c8e5f992502ee0f9bc2c04a61e981aae1d1#diff-9daf98386ed0f64373c442a413d33558 v display_info, riadok 55.
