### ISSUE TITLE
Nespravne zobrazovanie zisku a trzieb

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#16]
Napriklad pre SLOVNAFT MONTÁŽE A OPRAVY a.s. zobrazujeme:
Tržby v 2015: 94 132 416 € (+36%)   --- aj ked v skutocnosti su to trzby za 2016.

Treba fixnut
1. Data co dostavame z finstatu chybne konvertujeme do nasej mysql.company_stats tabulky. (Dano)
2. Updatenut frontend: Zobrazovat zisk/trzby z 2016 ak je to dostupne, inak z 2015. (Mito, Rasto)

**Comment by milutin** [comment]
Z backendu mi stale chodi:
trzby2014: 69243904
trzby2015: 94132416
zisk2014: 609499
zisk2015: 720104

Planujeme mat len posledne 2 roky?

**Comment by lenhardt** [comment]
idealne ked bude zobrazovat zisk2016 ak je available, inak zisk 2015. casom zacne z backendu chodit aj zisk2016.

**Comment by rejdi** [comment]
Pridal som podporu pre zisk2016 aj trzby2016 aj zamestnanci2016. Mozete teda doplnit tento parameter do backendu.

**Comment by lenhardt** [comment]
Toto bude tiez sucastou noveho frontendu. Zatvaram.
