### ISSUE TITLE
Pridat moznost si vybrat z menovcov v prepojeniach

### ISSUE THREAD

**Issue by milutin** [verejnedigital/verejne.digital#17]
<img width="720" alt="screen shot 2017-05-14 at 21 53 59" src="https://cloud.githubusercontent.com/assets/420964/26037264/05cc5e18-38f0-11e7-9c38-48e714190ed7.png">

Pridanie dropdown-ov pod pocet zaznamov alebo pod "Robert Kalinak"

**Comment by milutin** [comment]
Zacal som, zatial mam len loadovanie. Este UI, zmena eid z UI

**Comment by jakubukrop** [comment]
Ahoj, robis na tomto issue? Lebo by som to pozrel.

**Comment by lenhardt** [comment]
Nechal by som toto issue na neskor. Nech najskor prejdeme v produkcii na novy frontend.

Ma to totiz par nedoriesenych problemov. Casto totiz viac zaznamov reprezentuje toho isteho cloveka, len to nevieme rozlisit na zaklade mena a adresy (napriklad ak sa clovek prestahoval). Takze nie je uplne jasny benefit.

**Comment by lenhardt** [comment]
Riesenie menovcov je zatial nejasne, lebo casto sa kona o jednu a tu istu osobu len na roznych adresach. Najblizsie smerovanie je skor zobrazovanie krajsieho grafu prepojeni, ktore umoznuje zobrazovanie viac menovcov.
