### ISSUE TITLE
Zohnat marketaka a poprerabat texty.

### ISSUE THREAD

**Issue by rejdi** [verejnedigital/verejne.digital#18]
Ci uz na https://verejne.digital/obstaravania/index.html alebo aj hocikde inde, kde sa pouzivaju dlhsie texty... bolo by vhodne prerobit ich formu na nieco putavejsie. Vety ako "Pomocou algoritmov na strojové spracovanie textu hľadáme víťazov podobných obstarávaní v minulosti." su sice fajn ale v prvom kontakte by sa nemali vyskytovat, nakolko bezneho cloveka to skor odradi (povie si WTF?) ako zaujme.

**Comment by lenhardt** [comment]
+1

**Comment by lenhardt** [comment]
Mnozstvo textov v bete sme znizil, a mame blog https://medium.com/@verejne.digital. Closing for now ...
