### ISSUE TITLE
Doladenie frontendu Profil appky

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#19]
Optional veci mozme riesit aj po launchnuti.

Hlavna stranka:

- Na pomalsom internete trva zobrazenie dost dlho. Moze to byt tym, ze stahujeme 500 fotografii v prvom kroku. Chcelo by to trochu benchmarknut. Kedze to sortujeme az na frontende, tak si nestaci od servera vypytat menej dat, ale mozno by len stacilo zmenit logiku zobrazovnaia ked uz mame data pripravene, ze najskor zobrazit top 50 a az hned potom top 500. (je to scasti optional, ale bolo by dobre aspon rozumiet tomu ze preco to trva niekedy dlhsie)

Detail:

- [x] 1 V detaile vo vypise nehnutelnosti z NRSR zobrazujeme vacsinou aj obrazok grafu vyvoja nehnutelnosti. Ked vsak chyba (co je okej, lebo niekedy to nevieme sparsovat), tak je obrazok nedostupny a zobrazime altenativny text "majetok" Bolo by dobre tam radsej nic nezobrazit. Napriklad sa to stava tu: https://verejne.digital/profil/629
- [x] 2  border/tienovanie profilovej fotky
- [x] 3 horna lista viac ako v mushovom dizajne, ale radsej s linkom na zoznam a nie s hladacim boxom
- [x] 4  styl mapy verejne.digital s modrymi gulickami (optional)
- [x] 5 moznost preklikavat sa na predchadzajuce majetkove priznania -- data uz ma frontend k dispozicii (optional)

**Comment by milutin** [comment]
1. fixnuta https://github.com/verejnedigital/verejne.digital/commit/4b299d2201bfbe17b94de4e2c387c9f0cd1d7d69

**Comment by milutin** [comment]
3. fixnute https://github.com/verejnedigital/verejne.digital/commit/2c27c18ab46607c268c40ee4375b7dc45dc63d17

**Comment by milutin** [comment]
Ad. Loadovanie Hlavnej Stranky - na com sme sa dohodli? Mate API pre top 10? ja naloadujem naprv prvych 10 a potom zvysok?

**Comment by rejdi** [comment]
vybavene.
