### ISSUE TITLE
Nefungujece hladanie podla adresy

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#23]
Na verejne.digital, pri hladani pomocou adresy (v lavom hornom rohu) to nefuguje.

Zvyklo sa to presunut na hladanu adresu a zazoomovat na nu. Nefunguje to ani po zadani adresy v malom meste.

Nieco to muselo breaknut v poslednej dobe, nie je jasne, ze ci idu zle requesty na backend, nieco zlyhava tam, alebo sa nieco stalo na frontende .....

**Comment by lenhardt** [comment]
docasny problem, WAI

**Comment by rejdi** [comment]
Upresnim to... hladanie funguje, avsak po vybrati polozky za nejak blbo zoomne v mape a cela zosedne.

**Comment by lenhardt** [comment]
a znova mi to aj nefunguje ...

**Comment by rejdi** [comment]
@lenhardt skus to teraz. Ak ti to stale nepojde, skus mi dat step-by-step postup, info o prehliadaci kt. pouzivas a pripadne to skus aj v inom prehliadaci.

**Comment by lenhardt** [comment]
Toto je sucastou noveho beta frontendu, zatvaram na teraz.
