### ISSUE TITLE
Vysoky pocet entit bez mena

### ISSUE THREAD

**Issue by matejbalog** [verejnedigital/verejne.digital#241]
Mame vysoky pocet entit bez mena:
```
vd=> SELECT COUNT(*) FROM entities WHERE name='';
 count  
--------
 350466
```
Vzhladom na posledne zmeny su hlavnym podozrivym asi tabulky `organization_stakeholder_entries` a `organization_statutory_entries` zdroja RPO, a ich stlpec `person_formatted_name`.

**Comment by lenhardt** [comment]
pre referenciu, takto vyzeraju zdrojove data:

vd=> select full_name,person_formatted_name,person_given_names,person_family_names from organization_stakeholder_entries limit 30;
                              full_name                               |  person_formatted_name  | person_given_names  | person_family_names 
----------------------------------------------------------------------+-------------------------+---------------------+---------------------
                                                                      | Pavol Lužbeťák          | {Pavol}             | {Lužbeťák}
                                                                      | Daniel Yohannes Stewart | {"Daniel Yohannes"} | {Stewart}
                                                                      | Lukáš Závodský          | {Lukáš}             | {Závodský}
                                                                      | Mgr. Marcela Gatciová   | {Marcela}           | {Gatciová}
                                                                      | Ing. Marianna Orosová   | {Marianna}          | {Orosová}
                                                                      | Mgr. Jana Motyčková     | {Jana}              | {Motyčková}
                                                                      | Miroslav Žvásta         | {Miroslav}          | {Žvásta}
                                                                      | Mgr. Rudolf Jurčák      | {Rudolf}            | {Jurčák}
                                                                      | Michal Greguš           | {Michal}            | {Greguš}
 KEY Business s. r. o.                                                |                         | {}                  | {}
 Železnice Slovenskej republiky, Bratislava v skrátenej forme " ŽSR " |                         | {}                  | {}
 ATS CO., LTD                                                         |                         | {}                  | {}
                                                                      | Ing. Matej Kretík       | {Matej}             | {Kretík}
                                                                      | Mikuláš Soós            | {Mikuláš}           | {Soós}
                                                                      | Mamuka Lomidze          | {Mamuka}            | {Lomidze}
                                                                      | Dominika Moravcová      | {Dominika}          | {Moravcová}
                                                                      | Vladimír Barányi        | {Vladimír}          | {Barányi}
                                                                      | Filip Záhorec           | {Filip}             | {Záhorec}
                                                                      | Vladimír Sejka          | {Vladimír}          | {Sejka}
                                                                      | Jozef Laššák            | {Jozef}             | {Laššák}
                                                                      | Ivan Iliev Karaivanov   | {"Ivan Iliev"}      | {Karaivanov}
                                                                      | Ing. Pavol Jung         | {Pavol}             | {Jung}

**Comment by lenhardt** [comment]
|                         | {Dávid}             | {Jankech}

**Comment by lenhardt** [comment]
mali by sme pouzivat person_given_names a person_family_names:

vd=> select person_given_names,unnest(person_given_names) from organization_stakeholder_entries limit 5;
 person_given_names  |     unnest      
---------------------+-----------------
 {Pavol}             | Pavol
 {"Daniel Yohannes"} | Daniel Yohannes
 {Lukáš}             | Lukáš
 {Marcela}           | Marcela
 {Marianna}          | Marianna
