### ISSUE TITLE
V detaile linkujeme na orsr aj pri zivnostnikov - ktorych by sme mali linkovat na zrsr.sk

### ISSUE THREAD

**Issue by milutin** [verejnedigital/verejne.digital#302]

**Comment by lenhardt** [comment]
linkujeme na zrsr.sk, aj ked bez vyplnenia ICO. co je zlepsenie.

**Comment by milutin** [comment]
https://github.com/verejnedigital/verejne.digital/commit/4e7ca3f2701abaeb88f844052915194330147beb
