### ISSUE TITLE
Niektore institucie su povazovane za osoby a matchuju sa cez priezvisko s vela inymi

### ISSUE THREAD

**Issue by mmmaly** [verejnedigital/verejne.digital#305]
https://beta.verejne.digital/vyhladavanie?meno=CVTI%20SR

CVTI SR, adresa je zial nekompletna "Bratislava" a "SR" je asi povazovane za priezvisko, potom je matchnute s mnohymi dalsimi.

**Comment by lenhardt** [comment]
Toto by nemalo mat nic s adresou. Vztah pridavame len preto, ze SR povazujeme za priezvisko. Staci dat na to filter.

**Comment by matejbalog** [comment]
S adresou to súviselo len do tej miery, že keby tieto inštitúcie mali kompletné adresy (namiesto "Bratislava, SR"), tak by sa zgeokódovali na rozličné súradnice a teda hrany "Zhoda v priezvisku a adrese" by nevznikli.
