### ISSUE TITLE
Pocet stavieb a nekatualne grafy

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#314]
Preco v niektorych grafoch poctu nehnutelnosti su aj vysledky za 2017 a v niektorych len za 2016?
Tu chyba napriklad za 2017: https://beta.verejne.digital/profil/425

Pri Jarjabkovi ukazujeme ze ma 16 stavieb, co sa mi uplne nezda z toho co pise a tiez nema graf za 2017: https://beta.verejne.digital/profil/61

**Comment by matejbalog** [comment]
Fixed
