### ISSUE TITLE
Zmluvy sami so sebou

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#323]
Treba zistit kde je problem, je ich viac. Napriklad

select id, eid, supplier_eid from contracts where contract_id=3496532;
   id    |  eid   | supplier_eid 
---------+--------+--------------
 1170662 | 291274 |       291274

https://www.crz.gov.sk/index.php?ID=3496532

**Comment by matejbalog** [comment]
Na linkovanej zmluve ma objednavatel aj dodavatel uvedene rovnake ICO 17335345.

Celkovo mame 6269 takychto zmluv v aktualnych produkcnych datach:
```
vd=> SET search_path TO prod_20190202212658;
SET
vd=> SELECT COUNT(*) FROM contracts WHERE eid=supplier_eid;
 count
-------
  6269
```
Zatial co v zdrojovych datach:
```
vd=> SET search_path TO "source_ekosystem_CRZ_20190127000005";
SET
vd=> SELECT COUNT(*) FROM contracts WHERE contracting_authority_cin=supplier_cin;
 count
-------
  6674
```

**Comment by lenhardt** [comment]
problem je teda v zdrojovych datach. issue zatvaram.
