### ISSUE TITLE
Zmensit start-up time appiek

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#4]
Pri restarte serveru nabiehla hlavna verejne.digital appka asi polhodinu.

Treba skratit tento cas co najviac (pre zaciatok aspon pod 5 minut). Pomoze to pri vyvijani, a aj pri pripadnom vypadku.

**Comment by bundala** [comment]
Done. Hlavna appka startuje teraz radovo 30sekund.

Rozdelil som vytvaranie stavu / servovanie do dvoch krokov. generate_serving_data.py vypocita cely stav, vratane miest, okresov, mestkych casti a vsetkych potrebnych dat pre vsetky entity. Potom ich ulozi do adresara. Pri starte sa data priamo loaduju z adresara.
