### ISSUE TITLE
Nakonfigurovať novú aplikáciu client

### ISSUE THREAD

**Issue by matejbalog** [verejnedigital/verejne.digital#42]
Potrebovali by sme nakonfigurovať novú aplikáciu `client`, ktorá si pri štarte stiahne aktuálnu verziu (nového) frontendu, skompiluje ho a nakopíruje kompiláty do príslušného servovacieho adresára (beta alebo prod).

Nižšie je aktuálna verzia bash skriptu `update_new_frontend.sh`, ktorý trpí aspoň 4 nedostatkami:
- používa dočasný adresár v `/tmp/` (kvôli file permissions)
- deployuje do https://verejne.digital/beta namiesto https://beta.verejne.digital (keďže beta nám ešte úplne nefunguje, viď #10)
- hackuje súbor `client/package.json`, aby fungovalo aspoň referencovanie skompilovaného JavaScriptu (zrejme kvôli deployovaniu do https://verejne.digital/beta)
- nefungujú referencie na resources typu obrázky (kvôli deployovaniu do https://verejne.digital/beta)

```
# Create clean temporary directory
cd /tmp/
rm -rf frontend
mkdir frontend
cd frontend

# Clone repository
git clone https://github.com/verejnedigital/verejne.digital.git
cd verejne.digital/client

# Edit package.json [hack to make at least some paths work]
truncate -s-3 package.json
echo -e ",\n\"proxy\": \"https://verejne.digital/\",\n\t\"homepage\": \".\"}\n" >> package.json;

# Build frontend
yarn
yarn build

# Copy compiled frontend files into serving directory
sudo cp -R -v build/* /data/www/beta.verejne.digital/root/beta

# Delete temporary directory
rm -rf /tmp/frontend
```

**Comment by lenhardt** [comment]
Ako prvy krok by stacilo rozbehat beta.verejne.digital:

1. nginx konfiguracia ukazujuca na nejaky novy adresar
2. platny certifikat pre beta.verejne.digital
3. aby sa dal volat backend v ramci domeny potrebujeme aby requesty na beta.verejne.digital/api/* boli presmerovavane na spravne backendy (kludne produkcne, neskor mozme zmenit na beta verzie).

Franky, pozrel by si sa prosim na to? Alebo si ma niekedy zavolaj a nauc ma to ;-)
