### ISSUE TITLE
Prepisat frontend do reactu.

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#5]
Ciel je prepisat frontend do reactu.

Prvym krokom je zacat najjednoduchsou appkou Prepojenia.

**Comment by milutin** [comment]
Ok, zacal som s prepisovanim. Pouzil som https://github.com/facebookincubator/create-react-app co je najednoduchsia konfiguracia. Zatial som chcel pouzit co najmenej kniznic, takze som len pridal eslint na kontrolu javascriptovych chyb.

1. nainstalovat si npm
2. ```npm install``` na projekte k nainstalovaniu modulov co su v ```package.json```.
   - mozno treba instalovat ```create-react-app``` ak budu problemy, ale nemali by byt
3. ```npm start``` a v okne by sa malo otvorit ```localhost:3000```
   - cez proxy sa da vyhnut cross site scripting pocas developmentu
4. ```npm run lint``` na kontrolu chyb v kode.

Pushnem branch frontendToReact hned ako doriesim push.

**Comment by milutin** [comment]
Som si uvedomil ze pre AJAX pouzivam `fetch`, ktory je zatial podporovany len firefoxom a chromom. https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Treba tam pridat polyfill ktory doplni funkcionalitu pre ine browsre (IE, Safari) alebo pouzit kniznicu.

**Comment by milutin** [comment]
Prepisal som `display_info` do reactu, este mi tam ale chybaju

- [ ] isMapView
- [ ] rekurzivne prehladavanie pre subjekty vo vztahoch
- [ ] link na zaciatku je zbytocny, potom linky na zaciatku pred adresou su este nefunkcne

**Comment by milutin** [comment]
Pridal som do branch
- Zmeny url po hladani spojenia
- Rekurzivne prehladavanie - chce to lepsie UI, ale to sa asi spravi pri vacsom redesigne

**Comment by milutin** [comment]
Finalny [merge](https://github.com/verejnedigital/verejne.digital/commit/f1f2a3d6b44947847f74961683a7ae88cdad6669) - zvysok sa uz opravi a dokonci. Zatial budu v reacte len prepojenia, ine appky potrebuju pripravit backend (obstaravania) alebo nepotrebuju zatial react (verejne mapka)
