### ISSUE TITLE
naimplementovat nove /api/v/getInfos

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#50]
potrebujeme nahradu za aktualne /api/v/getInfo, ktora

- bude pouzivat nove data (idealne casom aj data z finstatu)
- bude na vstupe brat list entit, nielen 1 entitu (toto je uzitocne pre zobrazovanie zoznamu entit na adrese, vo vysledkoch vyhladavanie a vselikde inde, nech nemusime posielat N requestov na server naraz)

**Comment by matejbalog** [comment]
Prvá verzia `getInfos` beží; zobrazuje základné informácie o vyžiadaných entitách (meno, adresa, súradnice) a ich susedoch (related). Formát vidno napríklad na [https://verejne.digital/test.html](https://verejne.digital/test.html). Dajte prosím vedieť, ak by ste preferovali iný formát, alebo aké ďalšie dáta by bolo vhodné prioritne pridať.

**Comment by lenhardt** [comment]
Pridal by som tam nasledovne

1. Financne data z companyfinancials
2. Vznik/zanit z companyinfo
3. Suvisiace obstaravania z notices kde notices.id = noticesuppliers.notices_id pre noticesuppliers.eid matchujes nase eid. (Sidenote: mozno by sme mali zrusit celu noticesuppliers tabulku a mat suppliers_eid priamo v notices ...)

Skusim medzicasom zo source dat pridat aj zmluvy do produkcnych dat, potom mozme pridat aj tie.

**Comment by matejbalog** [comment]
Niektoré entity môžu vystupovať vo vysokom počte kontraktov:
```
SELECT supplier_eid, COUNT(*) AS cnt
FROM "prod_20180625122706".contracts
GROUP BY supplier_eid
ORDER BY cnt DESC
LIMIT 5;
 supplier_eid |  cnt   
--------------+--------
              | 363223
       294388 |  20805
       298611 |  20788
       297544 |  17672
      1569772 |  13938
```
V `/api/v/getInfos` teda asi chceme vracať len nejaké summaries (napr. počet kontraktov) a možno niekoľko `N` najnovších?

Inak v produkčnej tabuľke `companyfinancials` by sme nemohli mať `UNIQUE` constraint na páre `(eid, year)`?

**Comment by lenhardt** [comment]
👍 suhlasim s obomi.

dajme pocet kontraktov, ich celkova ohhadovana suma + N najvacsich + M najnovsich, pre N = 15, M =5 ? vzdy to mozu byt v buducnosti aj optional parametre API kebyze si frontend chce vypytat viac, ale kludne to mozme nateraz hard-code.

**Comment by matejbalog** [comment]
Pridal som do `api/v/getInfos` informácie z produkčných tabuliek `contracts`, `companyinfo`, `eufunds` a `notices`. Pre `notices` som zatiaľ nezoraďoval podľa hodnoty (`total_final_value_amount`) a nepočítal súčty, nakoľko tieto hodnoty zdá sa môžu byť uvedené v rôznych menách.

Chýbajú ešte informácie z tabuľky `companyfinancials`, prvý krok je ale asi teda ten `UNIQUE` constraint na `(eid, year)`.

**Comment by lenhardt** [comment]
Unique constraint do companyfinancials som pridal, aktualne sa rataju nove data uz s nim.

total_final_value_amount je v 99% pripadoch v eurach (vid https://colab.research.google.com/drive/1Mks1kPcm93TptUEudD-0Ff1jPkRsrJF1#scrollTo=12SrfLTRspcf), a ked nie je tak by som to ignoroval. Otazka je ze ci to osetrovat pri vytvarani produkcnych dat alebo pocas servovania.
