### ISSUE TITLE
Pridanie dat z FinStatu do novych produkcnych dat

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#52]
1. Najskor Mato Balog zmeni nacitavanie dat do source tabuliek tak aby tabulka mala stlpce s naozajstnymi nazvami, nielen col0, col1, ....

2. Potom Rasto prida generovanie produkcnych tabuliek z tychto source tabuliek.

**Comment by matejbalog** [comment]
Source tabuľka `company_stats` s dátami z FinStatu už má stĺpce so zmysluplnými názvami (viď [https://verejne.digital/data.html](https://verejne.digital/data.html)). Pôvodné názvy stĺpcov z CSV súboru sa pre prípad potreby naďalej ukladajú do tabuľky `column_names`.

**Comment by lenhardt** [comment]
v produkcnych datach uz mame tiez tabulku companyfinancials.
