### ISSUE TITLE
Pridat zakladne integracne testy

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#6]
Chybaju zakladne integracne testy
- pre backend (API cally).
- pre frontend (critical user journeys).

**Comment by matejbalog** [comment]
Backendy (API cally) aplikácií `verejne`, `prepojenia` a `kataster` majú vytvorené základné unit testy v skriptoch `test.py` vo svojich príslušných adresároch. Zatiaľ sa spúšťajú len manuálne z príkazového riadku `python test.py`.

**Comment by lenhardt** [comment]
spolu s verejne.digital/test.html by nam toto mohlo nateraz stacit
