### ISSUE TITLE
Konsolidovanie ludi do jednej entity

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#7]
Stava sa, ze mame na jednej adrese mena ludi, ktore reprezentuju jedneho cloveka.
Treba ich zlucit.

Napriklad.

Mgr. Janko Hrasko
Janko Hrasko

**Comment by matejbalog** [comment]
Ľudia s rovnakými menami, líšiacimi sa prípadne len v tituloch a pridaných názvoch živnosti, sú zlúčení.
