### ISSUE TITLE
Zdokumentovat data a API cally

### ISSUE THREAD

**Issue by lenhardt** [verejnedigital/verejne.digital#9]
Spravit prehlad aktualne pouzitelnych dat a API callov. Idealne aj so strucnym popisom.

**Comment by lenhardt** [comment]
Mohla by vzniknut nova aplikacia "data", hlavne pre vyvojarske ucely.

V prvom kroku
- na data.verejne.digital by sme mohi zobrazovat ake tabulky/data mame pouzitelne pre vyvoj 
(i.e, uz v normalizovanom stave, nie source tabulky)
- ako aktualne su tie data
- pridat automaticky mirroring dat z ekosystem.slovensko.digital (e.g. raz za tyzden stiahnut nove dumpy data od nich) a spravit ich pristupne pre vyvoj. (e.g. vo vlastnom namespace, uz teraz mame v psql namspaces mysql, obstaravania)

V druhom kroku
- zautomatizovat aktualizaciu dat -- tam mozno bude stacit ako zdroj miesto naisch starsich tabuliek zacat pouzivat ekosystemove data

P.S.: Doterajsie skripty k datam (e.g. normalizacia source tabuliek) este nie su na githube, co by sme mali napravit vytvorenim adresara data pre aplikaciu data

**Comment by jsuchal** [comment]
@lenhardt mozem sa spytat preco chcete mirrorovat data k sebe? Ved sql port je od nas odtvoreny? Co potrebujete urobit?

**Comment by lenhardt** [comment]
@jsuchal  je na to niekolko dovodov aj ked na niektore by mozno stacil sql port, kebyze vieme lepsie vyuzit jeho potencial (takze rady su velmi vitane).

- chceme aby sme vedeli data pouzivat rychlo na experimentaciu (i.e. napisat si python skript pre nejaky report kombinujuc uz nase existujuce data s ekosystem datami)
- niektore skripty co pustame nad nasimi datami (napriklad deduplikacne) trvaju hodiny a vedia uplne spomalit zvysok DB
- niektore data chceme pouzivat v produkcii, a tam si tazko predstavit zavisiet na DB beziacej na inom serveri
- skusal som sa -- davnejsie -- prihlasit aj priamo na vasu DB, ale ked som zacal pisat komplikovanejsie selecty, tak mi to nedovolilo (time-outovali)

Ciel je mat up-to-date kopiu u nas. Pravidelne stahovanie dumpov mi prislo jednoduchsie riesenie pre zaciatok, ako si pytat vzdy iba updates. I ked pri obstaravaniach is pytame uz teraz iba updates od poslednej zmeny takze tam to smeruje.

**Comment by jsuchal** [comment]
- toto si viem predstavit proste pripojenim na dve db. jednu nasu a jednu vasu. 
- deduplikacia - beriem - toto inak je nieco kde by sme mali spojit sily. my to napriklad robime tiez :)
- produkciu beriem tam je to jasne. 
- timeout vieme zvysit, staci sa ozvat, ale zase je pochopitelne, ze nechcem aby jeden to vymaxoval a zvysok to zabije.

**Comment by lenhardt** [comment]
Zatial aspon prva skupina hlavnych API callov:
https://verejne.digital/test.html

Nove test cases sa daju pridavat v https://github.com/verejnedigital/verejne.digital/blob/master/static/test.html

Casom by som tam chcel pridat aj popisy a dalsie testy.

**Comment by lenhardt** [comment]
Dokumentaciu coskoro pouzivanych dat uz mame vdaka Matovi tiez, je na 
https://verejne.digital/data.html
